### ISSUE TITLE
Please consider specifying a software license

### ISSUE THREAD

**Issue by tarsius** [PuercoPop/password-vault#4]
```
;;; License:
;; Copying is an act of love, please copy. ♡
```

That is a nice sentiment and because of that I hesitated to make this request, but could you please specify a proper license? This package is distributed on Melpa and we can only distribute packages that are licensed under a license that is compatible with that of Emacs (GPL-3.0-or-later).

If you choose that license, then you can specify it using:

```
;; SPDX-License-Identifier: GPL-3.0-or-later
```

If you pick another license, then please use the respective SPDX-License-Identifier, which you can find [here](https://spdx.org/licenses/).

By the way, the keyword lines should only be prefixed with two, instead of three, semicolons.

And even when you add the SPDX-License-Identifier keyword you should also [add a `LICENSE` file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) and add a permission statement:

```
;;; password-vault.el --- A Password manager for Emacs. -*- lexical-binding: t -*-

;; Author: Javier "PuercoPop" Olaechea <pirata@gmail.com>
;; URL: http://github.com/PuercoPop/password-vault
;; Version: 20131104
;; Keywords: password, productivity
;; Package-Requires: ((cl-lib "0.2") (emacs "24"))
;; SPDX-License-Identifier: GPL-3.0-or-later

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:
```

And finally, could you please also do this for `nyan-prompt`? It is not on Melpa but I do mirror it on the Emacsmirror, and that also requires a GPL-3.0-or-later compatible license.

Thanks!

**Comment by tarsius** [comment]
Friendly ping!

**Comment by PuercoPop** [comment]
@tarsius Done for this repo and nyan-prompt.

Btw I don't really use this package any more, instead I use the helm version that lives at https://github.com/emacs-pe/password-vault-

And thanks for magit/forge/minions and all the software you've written. I've recently started using borg instead of setting up a site-lisp dir, so thanks for that one too!

**Comment by tarsius** [comment]
Thanks!

Another one assimilated. :smiling_imp:
